### ISSUE TITLE
SSL cert for paddock website

### ISSUE THREAD

**Issue by durandom** [b4mad/racing#256]
* https://paddock.b4mad.racing/ should have a valid SSL cert. 
* http://paddock.b4mad.racing/ should redirect to https - maybe this is a OpenShift route thing - otherwise I'll try to configure that in django

**Comment by anton264** [comment]
You need to install cert-manager for openshift. https://github.com/cert-manager/openshift-routes I could try to help but it's hard to do without cluster access.

**Comment by durandom** [comment]
@anton264 thanks for having a look. The manifests for the target environment phobos are at https://github.com/b4mad/op1st-emea-b4mad/tree/main/manifests/environments/phobos 
with the cert-manager being at https://github.com/b4mad/op1st-emea-b4mad/blob/main/manifests/organizational-unit-scope/cluster-cert-manager.yaml

@goern will have a look at your PR 🙇

**Comment by anton264** [comment]
The issue is this line: https://github.com/b4mad/op1st-emea-b4mad/blob/main/manifests/environments/phobos/default-ingress-certificate.yaml#LL29C27-L29C27

The cert manager will only create certificates for this adress as you can see here: https://doc.crds.dev/github.com/jetstack/cert-manager/cert-manager.io/ClusterIssuer/v1#spec-acme-solvers-selector-dnsNames

If you inspect the certificate 
![image](https://github.com/b4mad/racing/assets/10194266/750ccbcd-66f8-4b34-bcfc-24ce4eccb986)

You can see that it is only issued for this adress, not for `paddock.b4mad.racing`

**Comment by goern** [comment]
@anton264 you analysis is correct. Gimme a few moments, and I’ll give some more background

**Comment by goern** [comment]
blocked by https://github.com/b4mad/op1st-emea-b4mad/issues/7

**Comment by durandom** [comment]
solved by #261 #263 and #267
